---
title: "Iteration: Unsolved homicide rates"
author: "Weijia Xiong"
date: "10/29/2019"
output: github_document
---

```{r setup, include = FALSE}
library(tidyverse)
library(rvest)
library(httr)
knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_minimal() + theme(legend.position = "bottom"))
set.seed(1)


```




## Read in the data

The data come from [here](https://github.com/washingtonpost/data-homicides). 

```{r}
homicide_df = 
  read_csv("data/homicide-data.csv", na = c("", "NA", "Unknown")) %>%
  mutate(
    city_state = str_c(city, state, sep = ", "),
    resolution = case_when(
      disposition == "Closed without arrest" ~ "unsolved",
      disposition == "Open/No arrest"        ~ "unsolved",
      disposition == "Closed by arrest"      ~ "solved"
    )
  ) %>% 
  filter(city_state != "Tulsa, AL") 
```


## Aggregate at the city level


```{r}
city_homicide_df =
  homicide_df %>% 
  select(city_state, resolution, disposition) %>% 
  group_by(city_state) %>% 
  summarize(
    hom_unsolved = sum(resolution == "unsolved"),
    hom_total = n()
  )
```


## For one city ...

... get the estimated rate of unsolved homicides and CI using `prop.test()` and `broom::tidy()`

```{r}
prop.test(
  x = city_homicide_df %>% filter(city_state == "Tulsa, OK") %>% pull(hom_unsolved), 
  n = city_homicide_df %>% filter(city_state == "Tulsa, OK") %>% pull(hom_total)) %>% 
  broom::tidy()
```


## Repeat for all cities

```{r}
homicide_results = 
  city_homicide_df %>% 
  mutate(
    prop_test = map2(.x = hom_unsolved, .y = hom_total, ~prop.test(x = .x, n = .y)),
    estimate_df = map(prop_test, broom::tidy)) %>% 
  select(city_state, estimate_df) %>% 
  unnest(estimate_df) %>% 
  select(city_state, estimate, conf.low, conf.high) %>% 
  mutate(city_state = fct_reorder(city_state, estimate))
```


## Visualize results


```{r}
homicide_results %>% 
  ggplot(aes(x = city_state, y = estimate)) + 
  geom_point() + 
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high)) +  
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
```
