---
title: "iteration_and_listcols"
author: "Weijia Xiong"
date: "10/29/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rvest)
set.seed(1)
```



```{r}
vec_numeric = 5:8
vec_char = c("My", "name", "is", "Jeff")
vec_logical = c(TRUE, TRUE, TRUE, FALSE)

l = list(vec_numeric = 5:8,
         mat         = matrix(1:8, 2, 4),
         vec_logical = c(TRUE, FALSE),
         summary     = summary(rnorm(1000)))
l
```


```{r}
l$vec_numeric

mean(l$vec_numeric)

l$summary

l[[1]]

l[[1]][1:3]

l[[2]]


```


```{r}
df = list(
  a = rnorm(20, 3, 1),
  b = rnorm(20, 0, 5),
  c = rnorm(20, 10, .2),
  d = rnorm(20, -3, 1)
)

df 
is.list(df)



```


## For loop

```{r}
df = tibble(
  a = rnorm(20, 3, 1),
  b = rnorm(20, 0, 5),
  c = rnorm(20, 10, .2),
  d = rnorm(20, -3, 1)
)

df 
is.list(df)
```

```{r}
mean_and_sd = function(x) {
  
  if (!is.numeric(x)) {
    stop("Argument x should be numeric")
  } else if (length(x) == 1) {
    stop("Cannot be computed for length 1 vectors")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)

  tibble(
    mean = mean_x, 
    sd = sd_x
  )
}



```


```{r}
mean_and_sd(df[[1]])

mean_and_sd(df[[2]])

mean_and_sd(df[[3]])

mean_and_sd(df[[4]])
```



```{r}
output = vector("list", length = 4)
```

Write our first for loop!

```{r}
for (i in 1:4) {
  
  output[[i]] = mean_and_sd(df[[i]])
  
}
output

```

## Map
```{r}
output = map(df, mean_and_sd)
output_median = map(df, median)
output_summary = map(df, summary)
output_median = map_dbl(df, median)
output = map_dfr(df, mean_and_sd)
output = map(df, ~mean_and_sd(.x))
```


## Napoleon!!

```{r}
url_base = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber="

vec_urls = str_c(url_base, 1:5) #Join multiple strings into a single string.

vec_urls
```
```{r}
read_page_reviews <- function(url) {
  
  h = read_html(url)
  
  title = h %>%
    html_nodes("#cm_cr-review_list .review-title") %>%
    html_text()
  
  stars = h %>%
    html_nodes("#cm_cr-review_list .review-rating") %>%
    html_text() %>%
    str_extract("\\d") %>%
    as.numeric()
  
  text = h %>%
    html_nodes(".review-data:nth-child(4)") %>%
    html_text()
  
  data_frame(title, stars, text)
}
```

```{r}
output = vector("list",length = 5)

for (i in 1:5) {
  output[[i]] = read_page_reviews(vec_urls[[i]])
}

output = map(vec_urls,read_page_reviews)

output
```



## Nest 

```{r}
weather = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2016-01-01",
    date_max = "2016-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY", 
                      USC00519397 = "Waikiki_HA",
                      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```


```{r}
weather_nest = 
  nest(weather, data = date:tmin)  # used nest by specifying a column range to collapse within remaining variable values

weather_nest
```

Is the list column really a list???

```{r}
weather_nest %>% pull(name)  # pull reserve the order.
weather_nest %>% pull(data)

weather_nest$data[[1]]


weather_nest %>% 
  unnest()
```

## Operations on list columns

Can I do useful things with a list column?

```{r}
central_park_df = weather_nest$data[[1]]

lm(tmax ~ tmin, data = weather_nest$data[[2]])
lm(tmax ~ tmin, data = weather_nest$data[[3]])
```

try a loop:

```{r}
output = vector("list",length = 3)

for (i in 1:3 ) {
  output[[i]] = lm(tmax ~ tmin, weather_nest$data[[i]])
}

output
```


```{r}

## function 
weather_lm = function(df) { 
  lm(tmax ~ tmin, data = df)
}
```

loop
```{r}
for (i in 1:3) { 
  output[[i]] = weather_lm(weather_nest$data[[i]])
}

output
```

map statement :
```{r}
output = map(weather_nest$data,weather_lm)
output
```

```{r}
## add linear models in nest data
weather_nest %>% 
  mutate(lin_models = map(data,weather_lm))
```

## Revisit napaleon ... again
```{r}
napaleon =
  tibble(
    page = 1:5,
    urls = str_c(url_base,page)
  ) %>% 
  mutate(
    reviews = map(urls,read_page_reviews)
  ) %>% 
  unnest(reviews) %>% 
  select(-urls)

napaleon
```


```{r}
dynamite_reviews = 
  tibble(page = 1:5,
         urls = str_c(url_base, page)) %>% 
  mutate(reviews = map(urls, read_page_reviews)) %>% 
  unnest()

lotr_cell_ranges = 
  tibble(
    movie = c("fellowship_ring", "two_towers", "return_king"),
    cells = c("B3:D6", "F3:H6", "J3:L6")
  )

lotr_tidy = 
  lotr_cell_ranges %>% 
  mutate(
    word_data = map(cells, ~readxl::read_excel("./data/LotR_Words.xlsx", range = .x))
  ) %>%  ## nest map 
  unnest(cols = word_data) %>%  ##展开
  janitor::clean_names() %>% 
  pivot_longer(
    female:male,
    names_to = "sex",
    values_to = "words") %>%
  mutate(race = str_to_lower(race)) %>% 
  select(movie, everything(), -cells)

lotr_tidy
```

