---
title: "writing functions"
author: "Weijia Xiong"
date: "10/24/2019"
output: github_document
---


```{r setup, include=FALSE}
library(tidyverse)
library(rvest)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_minimal() + theme(legend.position = "bottom"))
```


## Get started

We are going to write some functions.
```{r}
set.seed(1)
x = rnorm(30, mean = 4, sd = 2.3)
x_again = rnorm(30, mean = 6, sd = 0.3)
y = rnorm(30, mean = 4, sd = 0.3)
(x - mean(x)) / sd(x)
(x_again - mean(x_again)) / sd(x_again)
```

Now a function:

```{r}
z_scores = function(x) {
  
  z = (x - mean(x)) / sd(x)
  z
  
}

z_scores(x_again)
z_scores(x = y)
```


```{r, error=TRUE}
z_scores(3)
z_scores("my name is jeff")
z_scores(iris)
z_scores(sample(c(TRUE, FALSE), 25, replace = TRUE))
z_scores(c(TRUE,TRUE,FALSE,TRUE))  #= z_scores(c(1,1,0,1))

```


```{r, error=TRUE}
z_scores = function(x) {
  
  if (!is.numeric(x)) {
    stop("Argument x should be numeric")
  } else if (length(x) == 1) {
    stop("x should be longer than 3")
  }
  
  z = mean(x) / sd(x)
  
  z
}

z_scores(3)
z_scores(iris)
```


## Multiple outpus

return to list
```{r}
mean_and_sd = function(input_x) {
  
  if (!is.numeric(input_x)) {
    stop("Argument input_x should be numeric")
  } else if (length(input_x) < 3 ) {
    stop("input_x should be longer than 3")
  }
  
  mean_input = mean(input_x)
  sd_input = sd(input_x)

  list(mean = mean_input, 
       sd = sd_input,
       z_score = (input_x - mean(input_x)) / sd(input_x)
  )
}


mean_and_sd(y)
```

return to dataframe

```{r}
mean_and_sd = function(input_x) {
  
  if (!is.numeric(input_x)) {
    stop("Argument input_x should be numeric")
  } else if (length(input_x) == 1) {
    stop("Cannot be computed for length 1 vectors")
  }
  
  mean_input = mean(input_x)
  sd_input = sd(input_x)

  tibble(
    mean = mean_input, 
    sd = sd_input
  )
}

mean_and_sd(input_x = y)
```


```{r}

```


```{r}
sim_data  = tibble(
  x = rnorm(30, mean = 1, sd = 1),
  y = 2 + 3 * x + rnorm(30, 0, 1)
)

sim_data %>% 
  ggplot(aes(x = x, y = y)) +
  geom_point()

ls_fit = lm(y ~ x, data = sim_data)

beta0_hat = coef(ls_fit)[1]
beta_hat = coef(ls_fit)[2]
```


```{r}
sim_regression = function(n, beta0 = 2, beta1 =3){
  
  sim_data  = tibble(
  x = rnorm(n, mean = 1, sd = 1),
  y = beta0 + beta1 * x + rnorm(n, 0, 1)
)
  ls_fit = lm(y ~ x, data = sim_data)

  tibble(
  beta0_hat = coef(ls_fit)[1],
  beta_hat = coef(ls_fit)[2]
  )
}

sim_regression(n = 3000 ,beta0 = 17, beta1 = -3)
sim_regression(n = 3000, beta0 = 17)  #use default.
```


## html

```{r}
url = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber=1"

dynamite_html = read_html(url)

review_titles = dynamite_html %>%
  html_nodes("#cm_cr-review_list .review-title") %>%
  html_text()

review_stars = dynamite_html %>%
  html_nodes("#cm_cr-review_list .review-rating") %>%
  html_text()

review_text = dynamite_html %>%
    html_nodes(".review-text-content span") %>%
    html_text()

reviews = tibble(
  title = review_titles,
  stars = review_stars,
  text = review_text
)
```

```{r}
read_page_reviews <- function(url) {
  
  h = read_html(url)
  
  review_titles = h %>%
    html_nodes("#cm_cr-review_list .review-title") %>%
    html_text()
  
  review_stars = h %>%
    html_nodes("#cm_cr-review_list .review-rating") %>%
    html_text() %>%
    str_extract("\\d") %>%
    as.numeric()
  
  review_text = h %>%
    html_nodes(".review-text-content span") %>%
    html_text()
  
  tibble(
    title = review_titles,
    stars = review_stars,
    text = review_text
  )
}
```




```{r}
url_base = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber="
vec_urls = str_c(url_base, 1:5)

dynamite_reviews = bind_rows(
  read_page_reviews(vec_urls[1]),
  read_page_reviews(vec_urls[2]),
  read_page_reviews(vec_urls[3]),
  read_page_reviews(vec_urls[4]),
  read_page_reviews(vec_urls[5])
)
```



## Loading LoTR data

```{r}
fellowship_ring = readxl::read_excel("./data/LotR_Words.xlsx", range = "B3:D6") %>%
  mutate(movie = "fellowship_ring")

two_towers = readxl::read_excel("./data/LotR_Words.xlsx", range = "F3:H6") %>%
  mutate(movie = "two_towers")

return_king = readxl::read_excel("./data/LotR_Words.xlsx", range = "J3:L6") %>%
  mutate(movie = "return_king")

lotr_tidy = bind_rows(fellowship_ring, two_towers, return_king) %>%
  janitor::clean_names() %>%
  gather(key = sex, value = words, female:male) %>%
  mutate(race = str_to_lower(race)) %>% 
  select(movie, everything()) 
```


```{r}
lotr_load_and_tidy = function(path, range, movie_name) {
  
  df = readxl::read_excel(path, range = range) %>%
    janitor::clean_names() %>%
    gather(key = sex, value = words, female:male) %>%
    mutate(race = str_to_lower(race),
           movie = movie_name)
  
  df
  
}

lotr_tidy = 
  bind_rows(
    lotr_load_and_tidy("./data/LotR_Words.xlsx", "B3:D6", "fellowship_ring"),
    lotr_load_and_tidy("./data/LotR_Words.xlsx", "F3:H6", "two_towers"),
    lotr_load_and_tidy("./data/LotR_Words.xlsx", "J3:L6", "return_king")) %>%
  select(movie, everything()) 
```


```{r}
x = rnorm(25, 0, 1)

my_summary = function(x, summ_func) {
  summ_func(x)
}

my_summary(x, sd)
## [1] 0.8988712
my_summary(x, IQR)
## [1] 1.271572
my_summary(x, var)
## [1] 0.8079694
```



```{r}
f = function(x) {  ##  no y going to global to find y
  z = x + y
  z
}

x = 1
y = 2

f(x = y)

```

